---
# tasks file for kibana

- name: include secrets
  include_vars: "{{ item }}"
  no_log: true
  with_items:
    - "{{ inventory_dir }}/vars.yml"
    - "{{ inventory_dir }}/vault.yml"
    - "{{ inventory_dir }}/vault_files/efk.yml"
  ignore_errors: True
  tags: always

- name: main | get kibana user
  set_fact:
    kibana_user: "{{ item }}"
  no_log: true
  with_items: "{{ elastic_users }}"
  when: item["name"] == "kibanaserver"

- name: main | create project dir
  file:
    path: "{{ kibana_project_directory }}"
    state: directory
    recurse: yes

- name: main | template project
  template:
    src: "{{ item.src }}"
    dest: "{{ kibana_project_directory }}/{{ item.dest }}"
  with_items:
    - {src: "docker-compose.yml.j2", dest: "docker-compose.yml"}

- name: main | Running service
  docker_compose:
    project_src: "{{ kibana_project_directory }}"
    project_name: "{{ kibana_project_name }}"
    pull: yes
    restarted: yes
  register: output

- debug:
    var: output
