---
# defaults file for fluentbit
fluentbit_image: fluent/fluent-bit:latest
fluentbit_project_directory: /data/docker/fluentbit
fluentbit_project_name: fluentbit

elastic_host: "127.0.0.1"
elastic_port: "9200"
local_net: "192.168"
bind_ip: 0.0.0.0
bind_port: 24224

SERVICE:
  Flush: "5"
  Daemon: "Off"
  Log_Level: "debug"
  Buffer_Max_Size: "5MB"
  Buffer_Chunk_Size: "400k"

INPUTS:
  - Name: "forward"
    Listen: "{{ bind_ip }}"
    Port: "{{ bind_port }}"
    Buffer_Max_Size: "5Mb"
    Buffer_Chunk_size: "400k"

OUTPUTS:
  - Name: "es"
    Match: "*"
    Host: "{{ elastic_host }}"
    Port: "{{ elastic_port }}"
    HTTP_User: "{{ fluentbit_user['name'] }}"
    HTTP_Passwd: "{{ fluentbit_user['password'] }}"
    Type: "docker"
    Logstash_Format: "On"
    tls: "on"
    tls.verify: "off"
    Generate_ID: "on"
